# ==============================================================================
# 
#   L A Y O U T     P A G E     C O N F I G U R A T I O N
# 
# ==============================================================================
- title: Layout
  description:
    - To simplify the process of developing Web UI, Bootwrap uses the predefined layout which consists  of two elements <code>Page</code> and <code>Menu</code>.
    - <strong>Note:</strong> if your application does not require the top-level menu it can be discarded.
  image:
    file: layout.png
    height: 200

- title: Page
  constructor: Page(favicon=None, title=None, resources=None, menu=None, container=None)
  arguments:
    - ['favicon', 'str', 'the file name for the favorite icon displayed in a browser tab;']
    - ['title', 'str', 'the page title, displayed in a browser tab;']
    - ['resources', 'list', 'the The list of <code>Link</code>s and <code>Javascript</code>s to be loaded with the page;']
    - ['menu', 'Menu', 'the page top-level menu;']
    - ['container', 'WebComponent', 'the <code>WebComponent</code> for hosting page elements;']
  description:
    - The container could be any element inheriting <code>WebComponent</code> class. Typically for hosting  other custom interface elements is used  <code>Panel</code>.
  image:
    file: page.png
    height: 250
  code: |
    @left
    from bootwrap import Page

    page = Page(
      favicon=..., title=..., resources=..., menu=...,
      container=...
    )

- title: Menu
  constructor: Menu(logo=None, brand=None, anchors=None, actions=None)
  arguments:
    - ['logo', 'Image', 'the <code>Image</code> representing a company or organization logo;']
    - ['brand', 'Text', 'the <code>Text</code> representing a company, organization, or project name;']
    - ['anchors', 'list', 'the list of <code>Anchor</code> for navigation to the different pages from the top-level menu;']
    - ['actions', 'list', 'the list of <code>Button</code> for performing top-level actions such as login, logout, etc;']
  description:
    - The menu represents the top-level navigation bar containing anchors and actions allowing to switch between different application <code>Page</code>s. 
  image:
    file: menu.png
    height: 100
  code: |
    @left
    from bootwrap import Menu

    menu = Menu(
      logo=..., brand=..., anchors=...,  actions=...
    )

- title: Launch Offline
  description:
    - To run Web UI offline, you need to download CSS and JS scripts, store them locally, and instruct Page to load these scripts from a static location.
  code: |
    @left
    from bootwrap import Page

    # CSS (source URLs):
    #  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css                 
    #  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css               
    #  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css       

    # JS: (source URLs):
    #  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js                  
    #  - https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js          
    #  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js       
    #  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js        
    #  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/python.min.js 
    #  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/json.min.js   
    #  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/yaml.min.js   
    #  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/bash.min.js   

    page = Page(
      favicon=...,
      title=...,
      resources=[
        Link('/static/css/bootstrap.min.css'),                
        Link('/static/css/all.min.css'),              
        Link('/static/css/default.min.css')       
        Javascript('/static/js/jquery.min.js'),                 
        Javascript('/static/js/popper.min.js'),         
        Javascript('/static/js/bootstrap.bundle.min.js'),      
        Javascript('/static/js/highlight.min.js'),       
        Javascript('/static/js/languages/python.min.js'),
        Javascript('/static/js/languages/json.min.js'),  
        Javascript('/static/js/languages/yaml.min.js'),  
        Javascript('/static/js/languages/bash.min.js')   
      ],
      menu=...,
      container=...
    )



